source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'rails3-generators'
gem 'mongoid', '>= 2.0.0rc6'
gem 'bson_ext'
gem 'haml', '>= 3.0.18'
gem 'devise'
gem 'vinova_sunspot_mongoid', :require => 'sunspot_mongoid'
gem 'sunspot_rails', '~> 1.2.1'

group :development, :test, :cucumber do
  gem 'rspec-rails', '>= 2.0.0.beta.10'
  gem 'mongoid-rspec', :git => 'https://github.com/durran/mongoid-rspec.git'
  gem 'escape_utils'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber', '0.8.5'
  gem 'spork'
  gem 'launchy'
  gem 'autotest-rails'
  gem 'autotest'
  gem 'factory_girl_rails'
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'vagrant', '>= 0.7.0'
end
