defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: dinovet_development

test:
  <<: *defaults
  database: dinovet_test

cucumber:
  <<: *test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
